In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df  = pd.read_csv("SuperStoreOrders.csv")

In [ ]:
df.head(10)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011
5,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",55,2,0.1,15.342,1.80,Medium,2011
6,CA-2011-1510,2/1/2011,6/1/2011,Standard Class,Magdelene Morse,Consumer,Ontario,Canada,Canada,Canada,...,Technology,Machines,"Okidata Inkjet, Wireless",314,1,0.0,3.120,24.10,Medium,2011
7,IN-2011-79397,3/1/2011,3/1/2011,Same Day,Kean Nguyen,Corporate,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Appliances,"Hoover Microwave, White",276,1,0.1,110.412,125.32,Critical,2011
8,ID-2011-80230,3/1/2011,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Technology,Copiers,"Hewlett Wireless Fax, Laser",912,4,0.4,-319.464,107.10,Low,2011
9,IZ-2011-4680,3/1/2011,7/1/2011,Standard Class,Lindsay Williams,Corporate,Ninawa,Iraq,EMEA,EMEA,...,Furniture,Chairs,"Novimex Swivel Stool, Set of Two",667,4,0.0,253.320,81.26,High,2011

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [ ]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.dtypes

order_id           object
order_date         object
ship_date          object
ship_mode          object
customer_name      object
segment            object
state              object
country            object
market             object
region             object
product_id         object
category           object
sub_category       object
product_name       object
sales              object
quantity            int64
discount          float64
profit            float64
shipping_cost     float64
order_priority     object
year                int64
dtype: object

In [ ]:
df['order_date']=pd.to_datetime(df['order_date'],format='mixed', dayfirst=True)  # format = %d-%m-%y

In [ ]:
df['ship_date']=pd.to_datetime(df['ship_date'],format='mixed', dayfirst=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  datetime64[ns]
 2   ship_date       51290 non-null  datetime64[ns]
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(2), object(14)
memory usage: 8.2+ MB

In [ ]:
df.describe()

,order_date,ship_date,quantity,discount,profit,shipping_cost,year
count,51290,51290,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,2013-05-11 21:26:49.155780864,2013-05-15 20:42:42.745174528,3.476545,0.142908,28.641740,26.375915,2012.777208
min,2011-01-01 00:00:00,2011-01-03 00:00:00,1.000000,0.000000,-6599.978000,0.000000,2011.000000
25%,2012-06-19 00:00:00,2012-06-23 00:00:00,2.000000,0.000000,0.000000,2.610000,2012.000000
50%,2013-07-08 00:00:00,2013-07-12 00:00:00,3.000000,0.000000,9.240000,7.790000,2013.000000
75%,2014-05-22 00:00:00,2014-05-26 00:00:00,5.000000,0.200000,36.810000,24.450000,2014.000000
max,2014-12-31 00:00:00,2015-01-07 00:00:00,14.000000,0.850000,8399.976000,933.570000,2014.000000
std,NaN,NaN,2.278766,0.212280,174.424113,57.296804,1.098931

In [ ]:
df['category'].unique()

array(['Office Supplies', 'Furniture', 'Technology'], dtype=object)

In [ ]:
df['category'].value_counts()

category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [ ]:
df.columns=df.columns.str.replace(" ","_")

In [ ]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='object')

In [ ]:
# negative profit orders
loss_orders = df[df["profit"]<0]
print (loss_orders)

#this prints all the columns but if you want only the negative profit column you add ['profit']

              order_id order_date  ship_date       ship_mode  \
3      IT-2011-3647632 2011-01-01 2011-01-05    Second Class
8        ID-2011-80230 2011-01-03 2011-01-09  Standard Class
10       IN-2011-65159 2011-01-03 2011-01-07    Second Class
11       IN-2011-65159 2011-01-03 2011-01-07    Second Class
14       ID-2011-80230 2011-01-03 2011-01-09  Standard Class
...                ...        ...        ...             ...
51267  IT-2014-3715679 2014-12-31 2015-01-05    Second Class
51272  IT-2014-3715679 2014-12-31 2015-01-05    Second Class
51274     TU-2014-5170 2014-12-31 2015-01-04    Second Class
51275    ID-2014-54442 2014-12-31 2015-01-04  Standard Class
51289   CA-2014-156720 2014-12-31 2015-01-04  Standard Class

           customer_name      segment             state        country market  \
3           Eugene Moren  Home Office         Stockholm         Sweden     EU
8           Ken Lonsdale     Consumer          Auckland    New Zealand   APAC
10          Larry Blacks     Consumer  National Capital    Philippines   APAC
11          Larry Blacks     Consumer  National Capital    Philippines   APAC
14          Ken Lonsdale     Consumer          Auckland    New Zealand   APAC
...                  ...          ...               ...            ...    ...
51267           Jim Kriz  Home Office     North Brabant    Netherlands     EU
51272           Jim Kriz  Home Office     North Brabant    Netherlands     EU
51274  Valerie Dominguez     Consumer             Konya         Turkey   EMEA
51275    Muhammed Yedwab    Corporate  National Capital    Philippines   APAC
51289      Jill Matthias     Consumer          Colorado  United States     US

               region  ...         category sub_category  \
3               North  ...  Office Supplies        Paper
8             Oceania  ...       Technology      Copiers
10     Southeast Asia  ...  Office Supplies      Storage
11     Southeast Asia  ...        Furniture       Tables
14            Oceania  ...        Furniture       Chairs
...               ...  ...              ...          ...
51267         Central  ...  Office Supplies          Art
51272         Central  ...  Office Supplies      Binders
51274            EMEA  ...       Technology  Accessories
51275  Southeast Asia  ...       Technology  Accessories
51289            West  ...  Office Supplies    Fasteners

                                    product_name sales quantity  discount  \
3                    Enermax Note Cards, Premium    45        3      0.50
8                    Hewlett Wireless Fax, Laser   912        4      0.40
10                     Tenex Lockers, Industrial   338        3      0.45
11     Chromcraft Round Table, Adjustable Height   211        1      0.55
14                 Hon Rocking Chair, Set of Two   159        2      0.40
...                                          ...   ...      ...       ...
51267          BIC Pencil Sharpener, Fluorescent    30        2      0.50
51272              Avery Binder Covers, Recycled    23        4      0.50
51274                SanDisk Keyboard, Bluetooth    33        1      0.60
51275                   Memorex Mouse, Bluetooth    62        4      0.45
51289                        Bagged Rubber Bands     3        3      0.20

         profit  shipping_cost  order_priority  year
3      -26.0550           4.82            High  2011
8     -319.4640         107.10             Low  2011
10    -122.8005          33.75            High  2011
11     -70.3995          21.32            High  2011
14     -95.6760          10.07             Low  2011
...         ...            ...             ...   ...
51267   -9.6900           4.46            High  2014
51272   -6.4200           3.46            High  2014
51274  -25.2780           3.40          Medium  2014
51275  -37.2660           3.18          Medium  2014
51289   -0.6048           0.17          Medium  2014

[12543 rows x 21 columns]

In [ ]:
furniture_profit.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.77,4.70,Medium,2011
9,IZ-2011-4680,2011-01-03,2011-01-07,Standard Class,Lindsay Williams,Corporate,Ninawa,Iraq,EMEA,EMEA,...,Furniture,Chairs,"Novimex Swivel Stool, Set of Two",667,4,0.0,253.32,81.26,High,2011
12,ES-2011-4869686,2011-01-03,2011-01-07,Standard Class,Dorothy Dickinson,Consumer,England,United Kingdom,EU,North,...,Furniture,Bookcases,"Dania Corner Shelving, Traditional",854,7,0.0,290.43,12.56,Medium,2011
27,MX-2011-111255,2011-01-04,2011-01-09,Second Class,Russell Applegate,Consumer,Parana,Brazil,LATAM,South,...,Furniture,Bookcases,"Dania Classic Bookcase, Pine","1,648",6,0.0,609.84,109.13,Medium,2011
34,MX-2011-159373,2011-01-04,2011-01-08,Standard Class,Arthur Wiediger,Home Office,Santiago de Cuba,Cuba,LATAM,Caribbean,...,Furniture,Chairs,"SAFCO Chairmat, Black",38,1,0.0,6.88,4.25,Medium,2011

In [ ]:
df.to_csv("Cleaned_SuperStoreOrders.csv", index=False)